### ISSUE TITLE
Deleting courses in the UI

### ISSUE THREAD

**Issue by oskopek** [oskopek/StudyGuide#26]
@pribism:
> Also in the GUI it would be great if you could also delete subject from your internal database, I've imported it more times and I have it in the menu add course repeated few times.

**Comment by oskopek** [comment]
Should be fixed by 7d8cf1fbf0392e61571d26bcf127cd92aa37cbf5. Re-released, check the new release at https://github.com/oskopek/StudyGuide/releases/tag/n20160714. Please verify fix is working and close the issue.

**Comment by pribism** [comment]
Seems like it's working as I would expect. Cannot close the issue, because I am not an owner :)

**Comment by oskopek** [comment]
Oh, chute, sorry.
